name: flutter_chat_app_demo
description: A demo flutter project to showcase chat application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.0
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^7.0.2
  google_sign_in: ^6.1.0
  image_picker: ^0.8.7+5
  json_annotation: ^4.8.1
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
